version: "2"
services:
  jenkins-amd64:
    image: alexks02/jenkins:latest
    container_name: jenkins
    build:
      context: .
      dockerfile: ./Dockerfile.amd64
  jenkins-armhf:
    image: alexks02/jenkins:armhf
    container_name: jenkins
    build:
      context: .
      dockerfile: ./Dockerfile.armhf
